### ISSUE TITLE
Use "ssh-keyscan" instead of "ssh-keygen" to get known_hosts

### ISSUE THREAD

**Issue by gesinn-it-gea** [TIBHannover/application-setup-box-template#1]
https://github.com/TIBHannover/application-setup-box-template/wiki/Integration-of-automated-installation-into-GitLab-CI-CD-process#setup-ssh-configuration mentions to run `ssh-keygen -H -F YOUR-HOSTNAME` to get known_hosts information. This could lead to 

```
gitlab@confident14:~$ ssh-keygen -H -F confident14.test.service.tib.eu
do_known_hosts: hostkeys_foreach failed: No such file or directory
```
whreas `ssh-keyscan $(hostname --long)` works out-of-the-box. Docs should be updated.

**Comment by mirjan-hoffmann** [comment]
Thanks for the hint!

Yep, the `ssh-keygen` command just works, if the **known_hosts** file contains the related entry. Usually I execute the command on my local machine - since I have to connect to the system to be set up via ssh anyway, the known_hosts entry usually exists there.

Yes, to become independent from the **known_hosts** file we can switch to `ssh-keyscan`. However, I would not use `hostname --long`, since the command can then only be executed on the target system. Instead I would use the more general version `ssh-keyscan -H -t ecdsa-sha2-nistp256 YOUR-HOSTNAME`.

@gesinn-it-gea Does that fit?

**Comment by gesinn-it-gea** [comment]
sounds good!

**Comment by mirjan-hoffmann** [comment]
updated https://github.com/TIBHannover/application-setup-box-template/wiki/Integration-of-automated-installation-into-GitLab-CI-CD-process

-> closing
